### ISSUE TITLE
TypeError: must start with number, buffer, array or string

### ISSUE THREAD

**Issue by mahmed0715** [feross/whiteboard#7]
Hi,
i am trying to run the whiteboard application locally,
On browser it comes with this error and cant think further,
"TypeError: must start with number, buffer, array or string" :  

throw new TypeError('must start with number, buffer, array or string')
bundle.js line:1420

Its urgent,
Can you please check if this is really an issue..
Thanks in advance..

**Comment by feross** [comment]
I cannot reproduce this.
