### ISSUE TITLE
Peer events from tracker give duplicate peers

### ISSUE THREAD

**Issue by BenjaminLawson** [feross/whiteboard#9]
I'm not sure if it is intended tracker behavior or not, but some tracker events send peers that have already been sent. The whiteboard keeps adding these duplicate peers.

Steps to reproduce:
1. Open 2 whiteboard windows
2. Wait 5+ minutes until next peer event from tracker
3. Tracker sends peer that is a duplicate of the other peer, and it is added to peer array
4. Watch the peers array gradually grow out of control, and the usernames stack up!

![screenshot_295](https://cloud.githubusercontent.com/assets/3166039/18030919/f34183ec-6c7e-11e6-84b2-d7f926436ad9.jpg)

**Comment by feross** [comment]
Sorry -- this is unmaintained at the moment. You're welcome to send a PR and I will merge it.
